tox.ini
This un-garbles the test output, making actual warnings easier to spot, while still showing the captured output from tests when they do fail.
=> Let pytest capture test output

serverless.yaml
Make necessary packaging tweaks (taken from the discussion at https://github.com/Julian/jsonschema/issues/584) to make the `jsonschema` package work when running in AWS Lambda.
=> Make the `jsonschema` package work

serverless.yaml
Use dashes instead of underscores in Serverless function names (like `is-latest-edition` already did). This also makes the Lambda names nicer, such as `okdata-pipeline-dev-validate-json` instead of `okdata-pipeline-dev-validate_json`.
=> Make Serverless function names consistent

serverless.yaml
Fastparquet's test directory is pretty big, making our bundle exceed AWS Lambda's 250 MB size limit. Don't include it.
=> Don't include fastparquet's test dir in bundle

okdata/pipeline/converters/xls/main.py
Support using the default config for the XLS converter when it's missing from the pipeline task config.
=> XLS converter: Use default task config when missing

okdata/pipeline/common.py, okdata/pipeline/writers/kinesis/handler.py, test/writers/kinesis/handler_test.py
Look at `accessRights` instead of `confidentiality` when determining dataset access level.
=> DP-1629 Use `accessRights` instead of `confidentiality`

test/writers/kinesis/handler_test.py, tox.ini
A new version of Moto, a new round of breaking tests. :)
The formatting of the `ApproximateArrivalTimestamp` from `Kinesis:get_records()` was changed in Moto 2.0.2. Update our tests to reflect this.
=> Port to Moto 2.0.2

serverless.yaml
Increase the memory size for the `csv-to-parquet` pipeline to the new Lambda maximum of 10 GB.
=> DP-1988 Increase memory for `csv-to-parquet`

okdata/pipeline/validators/jsonschema_validator.py, test/validators/jsonschema_validator_test.py
This change adds handling of JSON validation errors w/o a path.
E.g. if given a schema requiring the keys `a` and `b`, an object like
`{"a": 123}` will give a validation error of `"'b' is a required property"`,
but would not have a path.
`path` and `relative_path` are empty for validation errors at root:
https://python-jsonschema.readthedocs.io/en/latest/errors/#jsonschema.exceptions.ValidationError.relative_path
=> DP-2162 Handle JSON errors at root

okdata/pipeline/validators/json/handler.py, test/validators/json/handler_test.py
The check for a single input is only relevant for S3 datasets.
=> DP-2189 Fix validation of multiple realtime JSON events

.gitignore, okdata/pipeline/validators/json/handler.py, okdata/pipeline/validators/json/s3_reader.py, serverless.yaml, test/validators/json/data/schema_array.json, test/validators/json/handler_test.py, test/validators/json/s3_reader_test.py
Feilmeldinger ved validering av JSON blir sendt til status-API-et.
<details>
<summary>
Eksempel i frontend - et array med JSON objects hvor object nr. 3 mangler en required key <code>created</code>.
</summary>
</details>
<details>
<summary>
Eksempel med <code>okdata</code> - JSON som ble lasta opp kunne ikke parses.
</summary>
</details>
NB: Feilmeldinger fra `jsonschema` blir ikke oversatt til norsk ettersom dette biblioteket ikke støtter oversettelser. Det vil kreve mye arbeid å sette opp og vedlikeholde en egen løsning for å oversette meldingene som biblioteket lager.
Ting for å teste i dev:
* Datasett: https://devportal-frontend.data-dev.oslo.systems/katalog/data/dp-2162-test-2
* Pipeline: https://github.com/oslokommune/okdata-pipeline-config/tree/7b643ada2a08fc85708c6f14a6924544324413 …
=> DP-2162 Send JSON validation errors to status API

test/converters/xls/main_test.py
The tests in `test/converters/xls/main_test.py` weren't running because the name of the class they were wrapped in didn't start with `Test`. Unwrapping them from the class revealed that they were all failing, so fix them up bit as well.
=> Run tests in `test/converters/xls/main_test.py`

okdata/pipeline/validators/csv/validator.py
The CSV validator is running too slowly on Deichman's three largest datasets (7,8 million lines and up). Skip validation for schema-less pipelines still, until the validator can handle them.
=> Skip CSV validation in schema-less pipelines again

package-lock.json, package.json, serverless.yaml
The common `pipeline_component_policy` will cover everything previously covered by the per-function policies `kinesis-writer-policy`, `lambda-invoker-policy`, and `s3-writer-policy`.
Depends on https://github.com/oslokommune/dataplatform-config/pull/49 being applied.
=> DP-2329 Drop per-function policies

tox.ini
The newest 0.17.0 version of the `repsonses` library breaks our tests in mysterious ways, so pin it to the previous 0.16.0 version. We don't use this library directly, but it's a sub-dependency of `moto`.
Possibly relevant: https://github.com/getsentry/responses/issues/467.
Also pin the top-level test dependencies to make the version cocktail more predictable.
=> Unbreak tests by pinning `responses`

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml, .github/workflows/pr-tests.yml, README.md, pyproject.toml, requirements.txt, serverless.yaml, tox.ini
Upgrade Python to 3.8 since NumPy 1.21 doesn't support Python 3.7.
Upgrade NumPy to 1.22 since Python 3.8 doesn't support NumPy 1.21.
=> Upgrade Python and NumPy

Makefile, package-lock.json, package.json, serverless.yaml
The `serverless-es-logs` plugin has been replaced with our own logging solution. Also it ran on an obsoleted runtime blocking deployment.
=> Remove `serverless-es-logs` plugin

requirements.txt, serverless.yaml, setup.py
Don't deploy libraries that are already pre-installed in the Lambda runtime in order to save space. This shaves off ~60 MB on the package deploy size (unzipped), making it deployable again.
Also lock the library versions to match those found in the Lambda runtime in order to make our local testing environment match it as closely as possible.
=> Rely on pre installed runtime libraries

requirements.txt, setup.py
Bump the okdata-sdk version requirement to remove a bunch of deprecation warnings in test runs.
=> Bump okdata-sdk requirement to remove warnings

okdata/pipeline/converters/xls/TableConverter.py, requirements.txt, setup.py, test/converters/xls/TableConverter_test.py
The xlrd library has dropped support for modern Excel files (.xlsx) since version 2, and is either way no longer maintained.
Replace it with openpyxl for XLSX support. The XLS legacy format that was supported by xlrd is no longer supported in okdata-pipeline.
=> Replace xlrd with openpyxl

okdata/pipeline/writers/s3/services.py, test/writers/s3/test_data.py, test/writers/s3/test_services.py
Preserve S3 "directories" when writing from one prefix to another in the S3 writer. The previous behavior was to flatten the file tree.
Old behavior (bad):
```
intermediate         processed
├── foo.txt     =>   ├── foo.txt
└── subdir           └── bar.txt
└── bar.txt
```
New behavior (good):
```
intermediate         processed
├── foo.txt     =>   ├── foo.txt
└── subdir           └── subdir
└── bar.txt          └── bar.txt
```
=> Preserve S3 "directories" in the S3 writer

Dockerfile, package-lock.json, package.json, requirements.txt, serverless.yaml, setup.py
Use a custom Docker image for the Lambda functions instead of the Python runtimes provided by AWS.
This allows package sizes above 250 MB, which will later let us deploy the rather large `deltalake` library.
It also gives us greater control over the installed dependencies, as the AWS runtimes come with a bunch of pre-installed libraries.
=> Dockerify Lambda runtimes

serverless.yaml
=> Fix Lambda docker image build for non-x86 architectures

serverless.yaml
Grant the Excel->CSV Lambda the resources necessary to handle typical Bydelsfakta data loads.
It seems that the new Docker-based runtimes require both more time and memory compared to the previous native Lambda ones.
=> Beef up the Excel->CSV Lambda

okdata/pipeline/converters/base.py
Make column type inference work for columns that don't have PyArrow datatypes assigned.
=> Make column type inference more robust

okdata/pipeline/validators/csv/parser.py, test/validators/csv/conftest.py, test/validators/csv/parser_test.py
Make CSV header parsing more robust by:
1. Ignoring whitespace at the beginning and end of header titles.
2. Detecting unknown headers and giving a proper error message, instead of crashing.
=> Make CSV header parsing more robust
